package br.cefetmg.implicare.model.domain.jpa;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaEstudo generated by hbm2java
 */
@Entity
@Table(name="area_estudo"
    ,schema="public"
)
public class AreaEstudo  implements java.io.Serializable {


     private int codAreaEstudo;
     private String nomAreaEstudo;
     private Set<Cargo> cargos = new HashSet<>(0);
     private Set<FormacaoAcademica> formacaoAcademicas = new HashSet<>(0);

    public AreaEstudo() {
    }

	
    public AreaEstudo(int codAreaEstudo, String nomAreaEstudo) {
        this.codAreaEstudo = codAreaEstudo;
        this.nomAreaEstudo = nomAreaEstudo;
    }
    public AreaEstudo(int codAreaEstudo, String nomAreaEstudo, Set<Cargo> cargos, Set<FormacaoAcademica> formacaoAcademicas) {
       this.codAreaEstudo = codAreaEstudo;
       this.nomAreaEstudo = nomAreaEstudo;
       this.cargos = cargos;
       this.formacaoAcademicas = formacaoAcademicas;
    }
   
     @Id 

    
    @Column(name="cod_area_estudo", unique=true, nullable=false)
    public int getCodAreaEstudo() {
        return this.codAreaEstudo;
    }
    
    public void setCodAreaEstudo(int codAreaEstudo) {
        this.codAreaEstudo = codAreaEstudo;
    }

    
    @Column(name="nom_area_estudo", nullable=false)
    public String getNomAreaEstudo() {
        return this.nomAreaEstudo;
    }
    
    public void setNomAreaEstudo(String nomAreaEstudo) {
        this.nomAreaEstudo = nomAreaEstudo;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="cargo_areaestudo", schema="public", joinColumns = { 
        @JoinColumn(name="cod_area_estudo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="cod_cargo", nullable=false, updatable=false) })
    public Set<Cargo> getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set<Cargo> cargos) {
        this.cargos = cargos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEstudo")
    public Set<FormacaoAcademica> getFormacaoAcademicas() {
        return this.formacaoAcademicas;
    }
    
    public void setFormacaoAcademicas(Set<FormacaoAcademica> formacaoAcademicas) {
        this.formacaoAcademicas = formacaoAcademicas;
    }




}


