package br.cefetmg.implicare.model.domain.jpa;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import br.cefetmg.implicare.model.domain.jpa.relacionamentos.FormacaoAcademicaId;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FormacaoAcademica generated by hbm2java
 */
@Entity
@Table(name="formacao_academica"
    ,schema="public"
)
public class FormacaoAcademica  implements java.io.Serializable {


     private FormacaoAcademicaId id;
     private AreaEstudo areaEstudo;
     private Candidato candidato;
     private String instituicaoEnsino;
     private String atividadesDesenvolvidas;
     private Date dataInicio;
     private Date dataTermino;
     private String descFormacaoAcademica;

    public FormacaoAcademica() {
    }

	
    public FormacaoAcademica(FormacaoAcademicaId id, Candidato candidato, String instituicaoEnsino, Date dataInicio, Date dataTermino) {
        this.id = id;
        this.candidato = candidato;
        this.instituicaoEnsino = instituicaoEnsino;
        this.dataInicio = dataInicio;
        this.dataTermino = dataTermino;
    }
    public FormacaoAcademica(FormacaoAcademicaId id, AreaEstudo areaEstudo, Candidato candidato, String instituicaoEnsino, String atividadesDesenvolvidas, Date dataInicio, Date dataTermino, String descFormacaoAcademica) {
       this.id = id;
       this.areaEstudo = areaEstudo;
       this.candidato = candidato;
       this.instituicaoEnsino = instituicaoEnsino;
       this.atividadesDesenvolvidas = atividadesDesenvolvidas;
       this.dataInicio = dataInicio;
       this.dataTermino = dataTermino;
       this.descFormacaoAcademica = descFormacaoAcademica;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cpf", column=@Column(name="cpf", nullable=false) ), 
        @AttributeOverride(name="seqFormacao", column=@Column(name="seq_formacao", nullable=false) ) } )
    public FormacaoAcademicaId getId() {
        return this.id;
    }
    
    public void setId(FormacaoAcademicaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_area_estudo")
    public AreaEstudo getAreaEstudo() {
        return this.areaEstudo;
    }
    
    public void setAreaEstudo(AreaEstudo areaEstudo) {
        this.areaEstudo = areaEstudo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cpf", nullable=false, insertable=false, updatable=false)
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    
    @Column(name="instituicao_ensino", nullable=false)
    public String getInstituicaoEnsino() {
        return this.instituicaoEnsino;
    }
    
    public void setInstituicaoEnsino(String instituicaoEnsino) {
        this.instituicaoEnsino = instituicaoEnsino;
    }

    
    @Column(name="atividades_desenvolvidas")
    public String getAtividadesDesenvolvidas() {
        return this.atividadesDesenvolvidas;
    }
    
    public void setAtividadesDesenvolvidas(String atividadesDesenvolvidas) {
        this.atividadesDesenvolvidas = atividadesDesenvolvidas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_termino", nullable=false, length=13)
    public Date getDataTermino() {
        return this.dataTermino;
    }
    
    public void setDataTermino(Date dataTermino) {
        this.dataTermino = dataTermino;
    }

    
    @Column(name="desc_formacao_academica")
    public String getDescFormacaoAcademica() {
        return this.descFormacaoAcademica;
    }
    
    public void setDescFormacaoAcademica(String descFormacaoAcademica) {
        this.descFormacaoAcademica = descFormacaoAcademica;
    }




}


