package br.cefetmg.implicare.model.domain.jpa;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import br.cefetmg.implicare.model.domain.jpa.relacionamentos.TelefoneId;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name="telefone"
    ,schema="public"
)
public class Telefone  implements java.io.Serializable {


     private TelefoneId id;
     private Usuario usuario;
     private char tipoTelefone;
     private int ddd;
     private Integer ramal;

    public Telefone() {
    }

	
    public Telefone(TelefoneId id, Usuario usuario, char tipoTelefone, int ddd) {
        this.id = id;
        this.usuario = usuario;
        this.tipoTelefone = tipoTelefone;
        this.ddd = ddd;
    }
    public Telefone(TelefoneId id, Usuario usuario, char tipoTelefone, int ddd, Integer ramal) {
       this.id = id;
       this.usuario = usuario;
       this.tipoTelefone = tipoTelefone;
       this.ddd = ddd;
       this.ramal = ramal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cpfCnpj", column=@Column(name="cpf_cnpj", nullable=false) ), 
        @AttributeOverride(name="seqTelefone", column=@Column(name="seq_telefone", nullable=false) ), 
        @AttributeOverride(name="numTelefone", column=@Column(name="num_telefone", nullable=false, length=9) ) } )
    public TelefoneId getId() {
        return this.id;
    }
    
    public void setId(TelefoneId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cpf_cnpj", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="tipo_telefone", nullable=false, length=1)
    public char getTipoTelefone() {
        return this.tipoTelefone;
    }
    
    public void setTipoTelefone(char tipoTelefone) {
        this.tipoTelefone = tipoTelefone;
    }

    
    @Column(name="ddd", nullable=false)
    public int getDdd() {
        return this.ddd;
    }
    
    public void setDdd(int ddd) {
        this.ddd = ddd;
    }

    
    @Column(name="ramal")
    public Integer getRamal() {
        return this.ramal;
    }
    
    public void setRamal(Integer ramal) {
        this.ramal = ramal;
    }




}


