package br.cefetmg.implicare.model.domain.jpa;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import br.cefetmg.implicare.model.domain.jpa.relacionamentos.VagaId;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vaga generated by hbm2java
 */
@Entity
@Table(name="vaga"
    ,schema="public"
)
public class Vaga  implements java.io.Serializable {


     private VagaId id;
     private Cargo cargo;
     private Empresa empresa;
     private Integer numVagas;
     private long cargaHoraria;
     private Double remuneracao;
     private String descVaga;
     private boolean statusVaga;
     private Set<CandidatoVaga> candidatoVagas = new HashSet<CandidatoVaga>(0);

    public Vaga() {
    }

	
    public Vaga(VagaId id, Cargo cargo, Empresa empresa, long cargaHoraria, boolean statusVaga) {
        this.id = id;
        this.cargo = cargo;
        this.empresa = empresa;
        this.cargaHoraria = cargaHoraria;
        this.statusVaga = statusVaga;
    }
    public Vaga(VagaId id, Cargo cargo, Empresa empresa, Integer numVagas, long cargaHoraria, Double remuneracao, String descVaga, boolean statusVaga, Set<CandidatoVaga> candidatoVagas) {
       this.id = id;
       this.cargo = cargo;
       this.empresa = empresa;
       this.numVagas = numVagas;
       this.cargaHoraria = cargaHoraria;
       this.remuneracao = remuneracao;
       this.descVaga = descVaga;
       this.statusVaga = statusVaga;
       this.candidatoVagas = candidatoVagas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codCargo", column=@Column(name="cod_cargo", nullable=false) ), 
        @AttributeOverride(name="seqVaga", column=@Column(name="seq_vaga", nullable=false) ), 
        @AttributeOverride(name="cnpj", column=@Column(name="cnpj", nullable=false) ), 
        @AttributeOverride(name="datPublicacao", column=@Column(name="dat_publicacao", nullable=false) ) } )
    public VagaId getId() {
        return this.id;
    }
    
    public void setId(VagaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cargo", nullable=false, insertable=false, updatable=false)
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cnpj", nullable=false, insertable=false, updatable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="num_vagas")
    public Integer getNumVagas() {
        return this.numVagas;
    }
    
    public void setNumVagas(Integer numVagas) {
        this.numVagas = numVagas;
    }

    
    @Column(name="carga_horaria", nullable=false)
    public long getCargaHoraria() {
        return this.cargaHoraria;
    }
    
    public void setCargaHoraria(long cargaHoraria) {
        this.cargaHoraria = cargaHoraria;
    }

    
    @Column(name="remuneracao", scale=0)
    public Double getRemuneracao() {
        return this.remuneracao;
    }
    
    public void setRemuneracao(Double remuneracao) {
        this.remuneracao = remuneracao;
    }

    
    @Column(name="desc_vaga")
    public String getDescVaga() {
        return this.descVaga;
    }
    
    public void setDescVaga(String descVaga) {
        this.descVaga = descVaga;
    }

    
    @Column(name="status_vaga", nullable=false)
    public boolean isStatusVaga() {
        return this.statusVaga;
    }
    
    public void setStatusVaga(boolean statusVaga) {
        this.statusVaga = statusVaga;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vaga")
    public Set<CandidatoVaga> getCandidatoVagas() {
        return this.candidatoVagas;
    }
    
    public void setCandidatoVagas(Set<CandidatoVaga> candidatoVagas) {
        this.candidatoVagas = candidatoVagas;
    }




}


