package br.cefetmg.implicare.model.domain.jpa.relacionamentos;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CandidatoVagaId generated by hbm2java
 */
@Embeddable
public class CandidatoVagaId  implements java.io.Serializable {


     private long cpf;
     private int seqVaga;
     private int codCargo;
     private long cnpj;
     private long datPublicacao;

    public CandidatoVagaId() {
    }

    public CandidatoVagaId(long cpf, int seqVaga, int codCargo, long cnpj, long datPublicacao) {
       this.cpf = cpf;
       this.seqVaga = seqVaga;
       this.codCargo = codCargo;
       this.cnpj = cnpj;
       this.datPublicacao = datPublicacao;
    }
   


    @Column(name="cpf", nullable=false)
    public long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(long cpf) {
        this.cpf = cpf;
    }


    @Column(name="seq_vaga", nullable=false)
    public int getSeqVaga() {
        return this.seqVaga;
    }
    
    public void setSeqVaga(int seqVaga) {
        this.seqVaga = seqVaga;
    }


    @Column(name="cod_cargo", nullable=false)
    public int getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(int codCargo) {
        this.codCargo = codCargo;
    }


    @Column(name="cnpj", nullable=false)
    public long getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(long cnpj) {
        this.cnpj = cnpj;
    }


    @Column(name="dat_publicacao", nullable=false)
    public long getDatPublicacao() {
        return this.datPublicacao;
    }
    
    public void setDatPublicacao(long datPublicacao) {
        this.datPublicacao = datPublicacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CandidatoVagaId) ) return false;
		 CandidatoVagaId castOther = ( CandidatoVagaId ) other; 
         
		 return (this.getCpf()==castOther.getCpf())
 && (this.getSeqVaga()==castOther.getSeqVaga())
 && (this.getCodCargo()==castOther.getCodCargo())
 && (this.getCnpj()==castOther.getCnpj())
 && (this.getDatPublicacao()==castOther.getDatPublicacao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCpf();
         result = 37 * result + this.getSeqVaga();
         result = 37 * result + this.getCodCargo();
         result = 37 * result + (int) this.getCnpj();
         result = 37 * result + (int) this.getDatPublicacao();
         return result;
   }   


}


