package br.cefetmg.implicare.model.domain.jpa.relacionamentos;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExperienciaProfissionalId generated by hbm2java
 */
@Embeddable
public class ExperienciaProfissionalId  implements java.io.Serializable {


     private long cpf;
     private int seqExperienciaProfissional;
     private int codCargo;

    public ExperienciaProfissionalId() {
    }

    public ExperienciaProfissionalId(long cpf, int seqExperienciaProfissional, int codCargo) {
       this.cpf = cpf;
       this.seqExperienciaProfissional = seqExperienciaProfissional;
       this.codCargo = codCargo;
    }
   


    @Column(name="cpf", nullable=false)
    public long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(long cpf) {
        this.cpf = cpf;
    }


    @Column(name="seq_experiencia_profissional", nullable=false)
    public int getSeqExperienciaProfissional() {
        return this.seqExperienciaProfissional;
    }
    
    public void setSeqExperienciaProfissional(int seqExperienciaProfissional) {
        this.seqExperienciaProfissional = seqExperienciaProfissional;
    }


    @Column(name="cod_cargo", nullable=false)
    public int getCodCargo() {
        return this.codCargo;
    }
    
    public void setCodCargo(int codCargo) {
        this.codCargo = codCargo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExperienciaProfissionalId) ) return false;
		 ExperienciaProfissionalId castOther = ( ExperienciaProfissionalId ) other; 
         
		 return (this.getCpf()==castOther.getCpf())
 && (this.getSeqExperienciaProfissional()==castOther.getSeqExperienciaProfissional())
 && (this.getCodCargo()==castOther.getCodCargo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCpf();
         result = 37 * result + this.getSeqExperienciaProfissional();
         result = 37 * result + this.getCodCargo();
         return result;
   }   


}


