package br.cefetmg.implicare.model.domain.jpa.relacionamentos;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FormacaoAcademicaId generated by hbm2java
 */
@Embeddable
public class FormacaoAcademicaId  implements java.io.Serializable {


     private long cpf;
     private int seqFormacao;

    public FormacaoAcademicaId() {
    }

    public FormacaoAcademicaId(long cpf, int seqFormacao) {
       this.cpf = cpf;
       this.seqFormacao = seqFormacao;
    }
   


    @Column(name="cpf", nullable=false)
    public long getCpf() {
        return this.cpf;
    }
    
    public void setCpf(long cpf) {
        this.cpf = cpf;
    }


    @Column(name="seq_formacao", nullable=false)
    public int getSeqFormacao() {
        return this.seqFormacao;
    }
    
    public void setSeqFormacao(int seqFormacao) {
        this.seqFormacao = seqFormacao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormacaoAcademicaId) ) return false;
		 FormacaoAcademicaId castOther = ( FormacaoAcademicaId ) other; 
         
		 return (this.getCpf()==castOther.getCpf())
 && (this.getSeqFormacao()==castOther.getSeqFormacao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCpf();
         result = 37 * result + this.getSeqFormacao();
         return result;
   }   


}


