package br.cefetmg.implicare.model.domain.jpa.relacionamentos;
// Generated 29/11/2018 03:11:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelefoneId generated by hbm2java
 */
@Embeddable
public class TelefoneId  implements java.io.Serializable {


     private long cpfCnpj;
     private int seqTelefone;
     private String numTelefone;

    public TelefoneId() {
    }

    public TelefoneId(long cpfCnpj, int seqTelefone, String numTelefone) {
       this.cpfCnpj = cpfCnpj;
       this.seqTelefone = seqTelefone;
       this.numTelefone = numTelefone;
    }
   


    @Column(name="cpf_cnpj", nullable=false)
    public long getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(long cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }


    @Column(name="seq_telefone", nullable=false)
    public int getSeqTelefone() {
        return this.seqTelefone;
    }
    
    public void setSeqTelefone(int seqTelefone) {
        this.seqTelefone = seqTelefone;
    }


    @Column(name="num_telefone", nullable=false, length=9)
    public String getNumTelefone() {
        return this.numTelefone;
    }
    
    public void setNumTelefone(String numTelefone) {
        this.numTelefone = numTelefone;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TelefoneId) ) return false;
		 TelefoneId castOther = ( TelefoneId ) other; 
         
		 return (this.getCpfCnpj()==castOther.getCpfCnpj())
 && (this.getSeqTelefone()==castOther.getSeqTelefone())
 && ( (this.getNumTelefone()==castOther.getNumTelefone()) || ( this.getNumTelefone()!=null && castOther.getNumTelefone()!=null && this.getNumTelefone().equals(castOther.getNumTelefone()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCpfCnpj();
         result = 37 * result + this.getSeqTelefone();
         result = 37 * result + ( getNumTelefone() == null ? 0 : this.getNumTelefone().hashCode() );
         return result;
   }   


}


